DEFAULT_NUMBER_OF_CLASSES = 6
DEFAULT_TRUE_NUMBER_OF_CLASSES = 3
DEFAULT_NUMBER_OF_FEATURES = 12
DEFAULT_NUMBER_OF_RECORDS_PER_CLASS = 500
DEFAULT_RANDOM_NUMBER_SEED = 0
DEFAULT_FEATURE_MEAN_RANGE = [0,1]
